# Generated by Django 4.2.1 on 2023-07-24 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='Release Date',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='organization',
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('rel_date__lte', datetime.date(2023, 7, 24))), name='Release Date', violation_error_message='Invalid Release Date'),
        ),
    ]
